# Rubocop
## NOTICE: Rubocop was disabled in pull request #8!

inherit_gem:
  bunto: .rubocop.yml

AllCops:
  TargetRubyVersion: 1.9
  Include:
    - lib/*.rb

  Exclude:
    - script/**/*
    - spec/**/*
