# Travis CI

sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.3.0
matrix:
  include:
    - rvm: 2.3.1
      env: BUNTO_VERSION=3.2.1
env:
  matrix:
    - BUNTO_VERSION=3.2.1
branches:
  only:
    - master
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/console
  - chmod a+x script/release
script: script/cibuild
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e6011bb9dce6d5c0753
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
    on_success: never
    on_failure: never
