# Travis CI

sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
env:
  matrix:
    - BUNTO_VERSION=1.0
branches:
  only:
    - master
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/console
  - chmod a+x script/release
script: script/cibuild
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e6011bb9dce6d5c0753
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
    on_success: never
    on_failure: never
